version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "php"
      - "dependencies"
      - "master"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    versioning-strategy: increase
    target-branch: "master"
    labels:
      - "npm"
      - "dependencies"
      - "master"
