#!/usr/bin/env sh
set -e

initialStuff() {
    if [ -z "$APP_KEY" ]; then
        echo "APP_KEY not found, generating application key..."
        export APP_KEY=$(php artisan key:generate --force --no-ansi --show)
    fi
    php artisan migrate --force --no-ansi -q; \
    php artisan storage:link; \
    php artisan icons:cache; \
    php artisan event:cache; \
    php artisan config:cache; \
    php artisan view:cache; \
    php artisan route:cache; \
    php artisan converge:index-search; \
    php artisan filament:cache-components; \
    php artisan filament:upgrade; \
    php artisan optimize:clear; \
    php artisan optimize;
}

if [ "$1" != "" ]; then
    exec "$@"
else
    initialStuff
    echo "Octane Server: Swoole"
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.swoole.conf
fi
